# Generated by Django 5.2.7 on 2026-02-14 15:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Leccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField(unique=True)),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('teoria', models.TextField(help_text='Explicación teórica')),
                ('ejemplos', models.TextField(help_text='Ejemplos prácticos')),
                ('nivel', models.CharField(choices=[('basico', 'Básico'), ('intermedio', 'Intermedio'), ('avanzado', 'Avanzado')], default='basico', max_length=20)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('activa', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Lecciones',
                'ordering': ['numero'],
            },
        ),
        migrations.CreateModel(
            name='Ejercicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField()),
                ('enunciado', models.TextField()),
                ('tipo', models.CharField(choices=[('multiple_choice', 'Opción Múltiple'), ('completar', 'Completar'), ('verdadero_falso', 'Verdadero/Falso')], max_length=50)),
                ('opciones', models.JSONField(blank=True, null=True)),
                ('respuesta_correcta', models.JSONField()),
                ('explicacion', models.TextField()),
                ('puntos', models.IntegerField(default=1)),
                ('leccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ejercicios', to='morfosintaxis.leccion')),
            ],
            options={
                'ordering': ['numero'],
            },
        ),
        migrations.CreateModel(
            name='ProgresoEstudiante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completada', models.BooleanField(default=False)),
                ('puntuacion', models.IntegerField(default=0)),
                ('fecha_completada', models.DateTimeField(blank=True, null=True)),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('leccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='morfosintaxis.leccion')),
            ],
            options={
                'verbose_name_plural': 'Progresos de Estudiantes',
                'unique_together': {('estudiante', 'leccion')},
            },
        ),
    ]
